export { default as Home } from './Home/Home';
export { default as AdminPanel } from './Admin/Admin';
export { default as FormPlace } from './FormPlace';
export { default as Navbar } from './Navbar';
export { default as AdminLogin } from './AdminLogin';
export { default as Footer } from './Footer';
export { default as NotFound } from './NotFound';
export { default as MapPage } from './MapPage/MapPage';
export { default as PlacePage } from './PlacePage/PlacePage';